version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      # - mvn versions:set -DremoveSnapshot
      - mvn clean package -Dmaven.test.skip=true 
      - mvn clean install -Dmaven.test.skip=true
      
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/api-teste-3.2.1.jar